// <auto-generated />
namespace _0303人事行政局放假資料.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create));
        
        string IMigrationMetadata.Id
        {
            get { return "202103030959141_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
